version: '3'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/data
    environment:
      - FLAG=${FLAG}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - internal

  bot:
    build: ./bot
    depends_on:
      - app
      - evil
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_URL=http://app:5000
      - ALLOWED_HOSTS=localhost,127.0.0.1
    networks:
      - internal
  
  evil:
    image: python:3.12-slim
    command: python -m http.server 8000 --directory /srv/evil
    ports:
      - "8000:8000"
    volumes:
      - ./evil:/srv/evil
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
    networks:
      - internal

volumes:
  db-data:

networks:
  internal:
    driver: bridge